### ISSUE TITLE
Null reference exception

### ISSUE THREAD

**Issue by michaellperry** [CloudNimble/BindingRedirectsDoctor#2]
### Installed product versions

- Visual Studio: 2017 Professional
- This extension: 1.0.1

### Description

The plugin threw a NullReferenceException when fixing binding redirects.

### Steps to recreate

1. Install the plugin
2. Restart Visual Studio
3. Open a WPF application with several NuGet and project dependencies
4. Right-click on App.config
5. Select "Fix Binding Redirects"

### Current behavior

```
Message: Object reference not set to an instance of an object.
   at CloudNimble.BindingRedirectDoctor.FixRedirectsCommandPackage.<>c__DisplayClass8_0.<FixBindingRedirects>b__1(Int32 i) in C:\projects\bindingredirectsdoctor\src\CloudNimble.BindingRedirectDoctor\FixRedirectsCommandPackage.cs:line 162
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
```

### Expected behavior

The binding redirects should be fixed.

**Comment by LasseSkytteKnudsen** [comment]
I get the same error... (same steps as described above)
VS 2017 (version 15.9.13)

**Comment by robertmclaws** [comment]
I believe we have resolved this issue. Please download or update to Version 1.1.1 from the VS Marketplace. Thanks!
